export const LOGIN_ACCOUNT_SUCCESS="LOGIN_ACCOUNT_SUCCESS";
export const LOGIN_ACCOUNT_FAILED="LOGIN_ACCOUNT_FAILED";

export const SIGNUP_ACCOUNT_SUCCESS="SIGNUP_ACCOUNT_SUCCESS";
export const SIGNUP_ACCOUNT_FAILED="SIGNUP_ACCOUNT_FAILED";
